db:
  image: postgres:9.3
  volumes:
    - ~/.docker-volumes/blog/db/:/varlib/postgresql/data
  expose:
    - '5432'

app:
  build: .
  volumes: 
    - .:/myapp
  ports:
    - '8080:3000'
  links:
    - db

